name: Deploy Cancel Upload Lambda

on:
  push:
    paths:
      - 'lambdas/cancel_upload/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambdas/cancel_upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Create ZIP file
        run: zip -r code.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-central-1:965638719397:function:words-cancel_upload \
            --zip-file fileb://code.zip