name: Deploy Admin Login

on:
  push:
    paths:
      - 'lambdas/admin/login/dist/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambdas/admin/login

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript project
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir lambda
          cp -r dist/* lambda/
          cp package.json package-lock.json lambda/
          npm ci --omit=dev --prefix lambda
          cd lambda && zip -r ../function.zip . && cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name words-admin_login \
            --zip-file fileb://function.zip